version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  churras_app:
    image: churras-kit-pro:latest ## Imagem da aplicação
    
    networks:
      - churras_rede ## Nome da rede interna

    environment:
      ## 🕒 Fuso Horário
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.churras_app.rule=Host(`app.churraschef.com.br`) ## Substitua pelo seu domínio
        - traefik.http.routers.churras_app.entrypoints=websecure
        - traefik.http.routers.churras_app.priority=1
        - traefik.http.routers.churras_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.churras_app.service=churras_app
        - traefik.http.services.churras_app.loadbalancer.server.port=80
        - traefik.http.services.churras_app.loadbalancer.passHostHeader=1

## --------------------------- ORION --------------------------- ##

networks:
  churras_rede: ## Nome da rede interna
    external: true
    name: churras_rede ## Nome da rede interna