// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfhwsishpusreoqqorlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmaHdzaXNocHVzcmVvcXFvcmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4OTk1NTksImV4cCI6MjA1MzQ3NTU1OX0.S0nQAOkJ7iK7Pxgps0H1fRC5_AK69BNUHa3A-7kjD9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});